### PR TITLE
esp/esp_driver/network_adapter: add .gitignore with build/ and sdkconfig

### PR DESCRIPTION
**Pull request by giuliobenetti**

### CODE REVIEW

**Comment by giuliobenetti** [comment]
I can’t sign CLA. This is what I get when I click the link, and I’ve tried on both Chrome and Firefox on PC and on mobile too:
924B4A80-CD1D-44B3-804F-4B5573524F91

**Comment by mantriyogesh** [comment]
Hello @giuliobenetti 
I did not understand intention of the pull request and how will it help users.
It is definitely good setting to keep if users need to do in their repo, however, it will be debatable if this will improve transparency of code

**Comment by giuliobenetti** [comment]
@mantriyogesh Usually open-source projects I deal with don’t have the project specific .config. They have a separate defconfig file that I recognize in sdkconfig.defaults. I don’t know if I’ve interpreted this correctly. I’m more used with mconf(Buildroot for example).
Anyway for my understanding sdkconfig file for me is the same as .config file and should not be versioned. Is it like that?

**Comment by giuliobenetti** [comment]
@mantriyogesh I've re-checked only now and you're right, sdkconfig must not be ignored. It's needed to build the firmware.
So I push force the commit with "build/" ignored only.

**Pull request closed without merging**
