### PR TITLE
Fix build with Linux 5.18

### PR DESCRIPTION
**Pull request by giuliobenetti**
Note that with this and PR #147 the Linux driver compiles up to Linux 6.0.

Can you merge both PRs?

### CODE REVIEW

**Comment by mantriyogesh** [comment]
Can you please let us know the transport combination you had used?

**Comment by giuliobenetti** [comment]
> Can you please let us know the transport combination you had used?

I’m not sure I’ve understood correctly the question. Maybe you mean how this and the other patch fixes the bugs? If yea everything is specified in the commit logs. Or otherwise can you explain me better? Thank you

**Comment by mantriyogesh** [comment]
What is the transport used?
one of:
SPI or SDIO or SPI+UART or SDIO+UART 
I mean, you might have checked one of these transports, but others might also need to be tested.
If you are able to build with them as well, it is plus for us. If not, we will have to take care while merging it over your commit.

**Comment by giuliobenetti** [comment]
> What is the transport used?
> one of:
> SPI or SDIO or SPI+UART or SDIO+UART
> I mean, you might have checked one of these transports, but others might also need to be tested.
> If you are able to build with them as well, it is plus for us. If not, we will have to take care while merging it over your commit.

Ooh, pardon. I’ve used SDIO only. SPI is still broken and I have it in my todo list to fix it.

**Pull request closed without merging**
