### PR TITLE
Fix build with Linux version >= 5.17

### PR DESCRIPTION
**Pull request by giuliobenetti**

### CODE REVIEW

**Comment by giuliobenetti** [comment]
Oops, I’ve had to filter per Linux version, not remove the 2 function calls. I’m going to update the commit soon.

**Comment by mantriyogesh** [comment]
Okay. I am curious why you had to remove do_exit() to even make it work on your Linux..

**Comment by giuliobenetti** [comment]
@mantriyogesh I've just updated the commit. My goal is to add support of this driver to Buildroot. Here you can find my WIP patch:
https://github.com/giuliobenetti/buildroot/commit/28fd8aa0e3b29902046fabad98c688c917f9ef7d

It's building fine for SDIO after adding the patch contained in this PR but SPI stil has problem I still have to find a work-around, like I've mentiond in #148

**Comment by giuliobenetti** [comment]
@mantriyogesh the previous patch was wrong, it didn't exit the thread, my bad. I've changed approach that is already used here:
https://github.com/lwfinger/rtl8723bu/blame/master/include/osdep_service_linux.h#L133-L137

**Comment by giuliobenetti** [comment]
Patch has been committed to I close this PR

**Pull request closed without merging**
