### PR TITLE
Fix build failure and warnings with idf version >= 5.0.0

### PR DESCRIPTION
**Pull request by giuliobenetti**

### CODE REVIEW

**Comment by giuliobenetti** [comment]
I can’t sign CLA. This is what I get when I click the link:
2D79B6AF-2A4C-44B6-BB29-01CE7A8DEA24

**Comment by mantriyogesh** [comment]
Hello @giuliobenetti ,

Thank you for bringing this CLA issue to our notice.
We will check what could be done ahead and let you know.
The problem is that without signing CLA, we cannot merge to master.

@cliffordjefferies had done a recent Pull request.
@cliffordjefferies, Did you also face similar issue for CLA? Any comment which could be helpful?

**Comment by cliffordjefferies** [comment]
The issue I had was the the email address used in local "git config" was old and differed from the one I used to log into github.com.
So signing the CLA cleared my new email but not the commits made with the old email.

The fix for me was to update the email address in git config and do the commits again in a fresh copy of the repo.

**Comment by mantriyogesh** [comment]
@giuliobenetti 
Could you please try the solution provided by @cliffordjefferies ?

**Comment by giuliobenetti** [comment]
@mantriyogesh @cliffordjefferies unfortunately I don’t have such issue. But my GitHub user started years ago with a different email and it’s 3 years I use a new one. So I’ve removed the secondary old email(that was not the primary) and I still have the same problem.
The commits are done with the same email of my GitHub user’s email. So that doesn’t solve the problem. Any other ideas?

**Comment by giuliobenetti** [comment]
@mantriyogesh @cliffordjefferies I’ve made it. I’ve removed my secondary email(that was my primary email) and re-added it.
That way solved the problem with CLA.

**Comment by mantriyogesh** [comment]
Thank you @giuliobenetti 
Appreciate your tie and input for raising the pull request.
We will merge it in master shortly.

**Comment by giuliobenetti** [comment]
@mantriyogesh Hi, I've just rebased to latest version. Can you please merge this PR?

**Comment by mantriyogesh** [comment]
Hello @giuliobenetti ,
We have queued your PR as we are yet supporting IDF till 4.4 maximum.
We will merge your submission to master, as we move ahead.
As part of accepting PR, we have to cross verify older IDF are backward compatible or not (as the nature of PR is IDF dependent)

**Comment by giuliobenetti** [comment]
I close this PR and reopen it for branch ESP-Hosted_MCU_Host

**Pull request closed without merging**
